---
description: controls how to dump entire request and response to log file. not recommended
  on production if performance is important
enabled: true
enableMask: true
request:
  headers: true
  cookies: true
  queryParameters: true
  body: true

response:
  headers: true
  cookies: true
  body: true
  statusCode: true
  contentLength: true
