# controls how to dump entire request and response to log file. not recommended
# on production if performance is important
enabled: true
enableMask: true
indentSize: 4
#if request: true, all supported configs under request will be true
request:
  headers: true
  filteredHeaders:
  #filters
  - Postman-Token
  - X-Correlation-Id
  cookies: true
  filteredCookies:
  - Cookie_Gmail
  queryParameters: true
  filteredQueryParameters:
  - itemId
  - a
  body: true

response:
  headers: true
  cookies: true
  body: true
  statusCode: true
